# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
  port: 8102

spring:
  application:
    name: microserver-calc

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.john: debug


eureka:
  client:
    service-url:
#      defaultZone: http://lisi:123@peer1:8781/eureka
      defaultZone: http://peer1:8781/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

custom:
  params:
    sleep-time: ${random.int(2000)}


management:
  security:
    enabled: false
